import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';

export default function Home() {
  const [style, setStyle] = useState(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>soful - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          soful
        </h1>

        <p className={styles.description}>
          select your learning style
        </p>

        <div className='styles.grid'>
          <Link href='./your-style/auditory' className='styles.card'>
            <h2>
              auditory
            </h2>
          </Link>
          <Link href='./your-style/kinesthetic' className='styles.card'>
            <h2>
              kinesthetic
            </h2>
          </Link>
          <Link href='./your-style/reading' className='styles.card'>
            <h2>
              reading
            </h2>
          </Link>
          <Link href='./your-style/visual' className='styles.card'>
            <h2>
              visual
            </h2>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
